version: "3"

services:
  asterisk:
    build:
      context: ./
      dockerfile: ./ubuntu/Dockerfile
    container_name: "asterisk"
    volumes:
      - ./asterisk/:/etc/asterisk/:ro
    expose:
      - 5060/udp
      - 10000-11000/udp
