{
 "title": "Docker overview",
 "description": "Docker container overview.",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Containers",
   "type": "stat",
   "description": "All running containers.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{name!=\"\"}[$__interval]) * 100)"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Network Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name!=\"\"}[$__interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name!=\"\"}[$__interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "cadvisor_version_info" },
    { "expr": "prometheus_build_info" },
    { "expr": "node_exporter_build_info" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{name!=\"\"}[$__interval]) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Receive and send traffic for each container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name!=\"\"}[$__interval])",
     "legendFormat": "Receive: {{ name }}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name!=\"\"}[$__interval])",
     "legendFormat": "Transmit: {{ name }}"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "description": "Receive and send network packets for each container.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_packets_total{name!=\"\"}[$__interval])",
     "legendFormat": "Receive: {{ name }}"
    },
    {
     "expr": "rate(container_network_transmit_packets_total{name!=\"\"}[$__interval])",
     "legendFormat": "Transmit: {{ name }}"
    }
   ]
  },
  {
   "title": "File System Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{name!=\"\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "File System Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{name!=\"\"}[$__interval])",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}