{
 "title": "SIP",
 "description": "Dashboard dedicated to SIP statistics.",
 "tags": [
  "heplify",
  "sip"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "Target",
    "query": "label_values(heplify_method_response, target_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Concurrent sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"200\"}[$__interval]))) /\n(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"INVITE\"}[$__interval])) -\n(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=~\"3.*|401|407\"}[$__interval])) or sum(up) * 0)) *\n160 * sum(rate(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"INVITE\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "stat",
   "description": "Calls Per Second.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"200\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CAPS",
   "type": "stat",
   "description": "Call Attempts Per Second.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"INVITE\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "description": "Registers Per Second.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$target\", method=\"REGISTER\", response=\"200\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "RAPS",
   "type": "stat",
   "description": "Register Attempts Per Second.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$target\", method=\"REGISTER\", response=\"REGISTER\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "stat",
   "description": "50* errors on invites.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=~\"50.*\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "INVITE per second",
   "type": "graph",
   "description": "Invites and the responses.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id) (rate(heplify_method_response{target_name=~\"$target\", method=\"INVITE\"}[$__interval]))",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "REGISTER per second",
   "type": "graph",
   "description": "Registers and the responses.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id) (rate(heplify_method_response{target_name=~\"$target\", method=\"REGISTER\"}[$__interval]))",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "KPI's",
   "type": "graph",
   "description": "Key Performance Indicators:\n  - Answer Seizure Ratio\n  - Network Efficiency Ratio\n  - Ineffective Session Attempts\n  - Session Completion Ratio\n  - Ineffective Registration Attempts",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"200\"}[$__interval])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"INVITE\"}[$__interval])) - \n(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=~\"3.*|401|407\"}[$__interval])) or sum(up) * 0)), 100)",
     "legendFormat": "ASR"
    },
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=~\"200|480|486|600|603\"}[$__interval])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"INVITE\"}[$__interval])) - \n(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=~\"3.*|401|407\"}[$__interval])) or sum(up) * 0)), 100)",
     "legendFormat": "NER"
    },
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=~\"408|500|503|504\"}[$__interval])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$$target\", method=\"INVITE\", response=\"INVITE\"}[$__interval]))), 100)",
     "legendFormat": "ISA"
    },
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$target\", method=\"BYE\", response=\"200\"}[$__interval])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=\"INVITE\"}[$__interval]))), 100)",
     "legendFormat": "SCR"
    },
    {
     "expr": "clamp_max(((sum(increase(heplify_method_response{target_name=~\"$target\", method=\"REGISTER\", response=~\"4.*|5.*|6.*\"}[$__interval])) - \nsum(increase(heplify_method_response{target_name=~\"$target\", method=\"REGISTER\", response=~\"401|402|407\"}[$__interval]))) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$target\", method=\"REGISTER\", response=\"REGISTER\"}[$__interval]))), 100)",
     "legendFormat": "IRA"
    }
   ]
  },
  {
   "title": "Invite Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id) (rate(heplify_method_response{target_name=~\"$target\", method=\"INVITE\", response=~\"4.*|50.*\" }[$__interval]))",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "graph",
   "description": "All SIP methods and their responses.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(direction,node_id) (rate(heplify_method_response{target_name=~\"$target\"}[$__interval]))",
     "legendFormat": "{{ method }} {{ response }}"
    }
   ]
  }
 ]
}